# TODO Consider sharing with https://github.com/hazelcast/hazelcast-docker/blob/9466756692553823bfca159b28e007e27cf06730/.github/workflows/tag_image_push.yml#L179-L212
name: Download Hazelcast Distribution
inputs:
  vars-as-json:
    description: 'Vars as JSON - https://github.com/orgs/community/discussions/49689#discussioncomment-6398261'
    required: true
  hz_version:
    required: true
  distribution:
    required: true
runs:
  using: "composite"
  steps:
    - id: maven-repo
      uses: ./.github/actions/get-hz-dist-maven-repo
      with:
        vars-as-json: ${{ toJSON(inputs.vars-as-json) }}
        hz_version: ${{ inputs.hz_version }}
        distribution: ${{ inputs.distribution }}

    - shell: bash
      run: |
        mvn \
          org.apache.maven.plugins:maven-dependency-plugin:2.10:get \
          -DremoteRepositories="${{ steps.maven-repo.outputs.repo_url }}" \
          -DgroupId="com.hazelcast" \
          -DartifactId="${{ inputs.distribution }}-distribution" \
          -Dversion="${{ inputs.hz_version }}" \
          -Dpackaging="tar.gz" \
          -Dtransitive=false \
          -Ddest="distribution.tar.gz" \
          --batch-mode \
          --no-transfer-progress
