#!/usr/bin/env bash

HAZELCAST_VERSION=${project.version}
PRG="$0"
PRGDIR="$(dirname "$(realpath $PRG)")"
export HAZELCAST_HOME=${HAZELCAST_HOME:-$(cd "$PRGDIR/.." >/dev/null; pwd -P)}

banner () {
    echo "  _   _               _               _   "
    echo " | | | | __ _ _______| | ___ __ _ ___| |_ "
    echo " | |_| |/ _\` |_  / _ \ |/ __/ _\` / __| __|"
    echo " |  _  | (_| |/ /  __/ | (_| (_| \__ \ |_ "
    echo " |_| |_|\__,_/___\___|_|\___\__,_|___/\__|"
    echo "                                          "
    echo " V. ${HAZELCAST_VERSION}"
}

version() {
    echo ${HAZELCAST_VERSION}
}

usage() {
    CMD=$(basename $0)
    echo "$CMD controls Hazelcast member instance(s) on the local machine"
    echo
    echo "Usage:  $CMD COMMAND"
    echo
    echo "Basic Commands:"
    echo "  start       start Hazelcast member"
    echo "  status      display process status for Hazelcast member"
    echo "  stop        stop Hazelcast member"
    echo
    echo "Other Commands:"
    echo "  banner      display Hazelcast banner"
    echo "  usage       display usage information"
    echo "  version     print Hazelcast version"
}

if [[ $1 = '' ]]; then
    banner
    usage
    exit 0
fi

case "$1" in
    banner)
        banner
        ;;
    start)
        ${HAZELCAST_HOME}/bin/start.sh;;
    status)
        ${HAZELCAST_HOME}/bin/status.sh;;
    stop)
        ${HAZELCAST_HOME}/bin/stop.sh;;
    --help | help | -h | usage)
        usage
        ;;
    version)
        version
        ;;
    *)
        usage
        echo
        echo "$CMD: '$1' is not a valid command."
esac
