#!/usr/bin/env bash

HAZELCAST_VERSION=${project.version}
PRG="$0"
PRGDIR="$(dirname "$(realpath $PRG)")"
export HAZELCAST_HOME=${HAZELCAST_HOME:-$(cd "$PRGDIR/.." >/dev/null; pwd -P)}

usage() {
    CMD=$(basename $0)
    echo "  _   _               _               _   "
    echo " | | | | __ _ _______| | ___ __ _ ___| |_ "
    echo " | |_| |/ _\` |_  / _ \ |/ __/ _\` / __| __|"
    echo " |  _  | (_| |/ /  __/ | (_| (_| \__ \ |_ "
    echo " |_| |_|\__,_/___\___|_|\___\__,_|___/\__|"
    echo "                                          "
    echo " V. ${HAZELCAST_VERSION}"
    echo
    echo "Usage:  $CMD COMMAND"
    echo
    echo "A tool for running Hazelcast member instance(s) on the local machine"
    echo
    echo "Commands:"
    echo "  start       starts Hazelcast member"
    echo "  status      show process status for Hazelcast member"
    echo "  stop        stops Hazelcast member"
}

if [[ $1 = '' ]]; then
  usage
  exit 0
fi

case "$1" in
    start)
        ${HAZELCAST_HOME}/bin/start.sh;;
    status)
        ${HAZELCAST_HOME}/bin/status.sh;;
    stop)
        ${HAZELCAST_HOME}/bin/stop.sh;;
    *)
        usage
esac
