name: Get Hazelcast Distribution URL
inputs:
  repo-vars-as-json:
    description: 'Repo Vars as JSON - not inherited in composite actions - see https://github.com/orgs/community/discussions/49689#discussioncomment-6398261'
    required: true
  hz_version:
    description: 'Hazelcast version'
    required: true
  distribution:
    description: 'Distribution type: "hazelcast" or "hazelcast-enterprise"'
    required: true
outputs:
  url:
    value: ${{ steps.get_url.outputs.url }}
runs:
  using: "composite"
  steps:
    - id: maven-repo
      uses: ./.github/actions/get-hz-dist-maven-repo
      with:
        repo-vars-as-json: ${{ toJSON(inputs.repo-vars-as-json) }}
        hz_version: ${{ inputs.hz_version }}
        distribution: ${{ inputs.distribution }}

    - id: get_url
      shell: bash
      run: |
        # Detect if the repo definition specifies authentication via a Maven server (e.g. "my-private-repo::::https://example.com/private-repo")
        if [[ "${{ steps.maven-repo.outputs.repo_url }}" == *[!:]::::* ]]; then
          echo "Distribution URL requires authentication, aborting!";
          exit 1;
        else
          echo "url=${{ steps.maven-repo.outputs.repo_url }}/com/hazelcast/${{ inputs.distribution }}-distribution/${{ inputs.hz_version }}/${{ inputs.distribution }}-distribution-${{ inputs.hz_version }}.tar.gz" >> ${GITHUB_OUTPUT}
        fi
