name: Get Hazelcast Distribution Maven Repository
inputs:
  repo-vars-as-json:
    description: 'Repo Vars as JSON - not inherited in composite actions - see https://github.com/orgs/community/discussions/49689#discussioncomment-6398261'
    required: true
  hz_version:
    description: 'Hazelcast version'
    required: true
  distribution:
    description: 'Distribution type: "hazelcast" or "hazelcast-enterprise"'
    required: true
outputs:
  repo_url:
    value: ${{ steps.get_repo_url.outputs.repo_url }}
runs:
  using: "composite"
  steps:
    - id: get_repo_url
      shell: bash
      run: |
        case "${{ inputs.distribution }}" in
            "hazelcast")
              if [[ "${{ inputs.hz_version }}" == *"SNAPSHOT"* ]]; then
                repo_var_name=MAVEN_OSS_SNAPSHOT_REPO
              else
                repo_var_name=MAVEN_OSS_RELEASE_REPO
              fi
            ;;
            "hazelcast-enterprise")
              if [[ "${{ inputs.hz_version }}" == *"SNAPSHOT"* ]]; then
                repo_var_name=MAVEN_EE_SNAPSHOT_REPO
              else
                repo_var_name=MAVEN_EE_RELEASE_REPO
              fi
            ;;
            *)
            echoerr "Unsupported repository behaviour for ${{ inputs.distribution }}" ; return 1
            ;;
        esac

        echo "repo_url=$(jq --raw-output .${repo_var_name} <<< '${{ fromJSON(inputs.repo-vars-as-json) }}')" >> ${GITHUB_OUTPUT}
