hazelcast:
  cluster-name: dev
  properties:
    hazelcast.socket.bind.any: false
  network:
    interfaces:
      enabled: true
      interfaces:
        - 127.0.0.1
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
