name: Authenticate JFrog
inputs:
  aws-role-to-assume:
    description: 'AWS Role to assume for accessing secrets'
    required: true
runs:
  using: "composite"
  steps:
     # Should be a relative local path, but doesn't resolve when called from another repo
    - uses: hazelcast/docker-actions/get-jfrog-credentials@expose-jfrog-credentials
      id: jfrog
      with:
        aws-role-to-assume: ${{ inputs.aws-role-to-assume }}
        jfrog-oidc-provider-name: ${{ github.repository_owner }}-write-dev-account

    - shell: bash
      run: |
        echo "JFROG_USERNAME=${{ steps.jfrog.outputs.user }}" >> ${GITHUB_ENV}
        echo "JFROG_TOKEN=${{ steps.jfrog.outputs.token }}" >> ${GITHUB_ENV}
