#!/usr/bin/env bash

# templates meant to be resolved at build or install time
HAZELCAST_VERSION=${hazelcast_version}

#
PRG="$0"
PRGDIR="$(dirname "$(realpath $PRG 2>/dev/null || readlink -f $PRG)")"
export HAZELCAST_HOME=${HAZELCAST_HOME:-$(cd "$PRGDIR/.." >/dev/null; pwd -P)}

function banner () {
    echo "  _   _               _               _   "
    echo " | | | | __ _ _______| | ___ __ _ ___| |_ "
    echo " | |_| |/ _\` |_  / _ \ |/ __/ _\` / __| __|"
    echo " |  _  | (_| |/ /  __/ | (_| (_| \__ \ |_ "
    echo " |_| |_|\__,_/___\___|_|\___\__,_|___/\__|"
    echo "                                          "
    echo " V. ${HAZELCAST_VERSION}"
}

function version() {
    echo ${HAZELCAST_VERSION}
}

function usage() {
    CMD=$(basename $0)
    echo "$CMD controls Hazelcast member instance(s) on the local machine"
    echo
    echo "Usage:  $CMD COMMAND"
    echo
    echo "Basic Commands:"
    echo "  start       start a Hazelcast member"
    echo "  status      display process status for started members"
    echo "  stop        stop a member"
    echo
    echo "Other Commands:"
    echo "  banner      display banner"
    echo "  logs        display logs for a member"
    echo "  list        print started members IDs"
    echo "  usage       display usage information"
    echo "  version     print Hazelcast version"
}

if [[ $1 = '' ]]; then
    banner
    usage
    exit 0
fi

COMMAND=$1
shift
case "$COMMAND" in
    banner)
        banner
        ;;
    logs)
        ${HAZELCAST_HOME}/bin/logs.sh "$@";;
    list)
        ${HAZELCAST_HOME}/bin/list.sh "$@";;
    start)
        ${HAZELCAST_HOME}/bin/start.sh "$@";;
    status)
        ${HAZELCAST_HOME}/bin/status.sh "$@";;
    stop)
        ${HAZELCAST_HOME}/bin/stop.sh "$@";;
    usage | help | --help | -h)
        usage
        ;;
    version)
        version
        ;;
    *)
        usage
        echo
        echo "$CMD: '$COMMAND' is not a valid command."
esac
