name: Publish RPM package

on:
  workflow_call:
    inputs:
      HZ_VERSION:
        description: 'Version of Hazelcast to build the image for, this is the Maven version - e.g.: 5.0.2 or 5.1-SNAPSHOT'
        required: true
        type: string
      HZ_DISTRIBUTION:
        description: 'Distribution to be built: hazelcast or hazelcast-enterprise'
        required: true
        type: string
      PACKAGE_VERSION:
        description: 'Version of the package e.g. 5.1.1, 5.1.1-1, defaults to HZ_VERSION'
        type: string
      ENVIRONMENT:
        description: 'Environment to use'
        required: true
        type: string
      JAVA_VERSION:
        description: 'Java version to use'
        required: true
        type: string

concurrency:
  group: 'rpm-${{ inputs.HZ_VERSION }}-${{ inputs.HZ_DISTRIBUTION }}'

jobs:
  rpm:
    name: RPM (`${{ inputs.HZ_DISTRIBUTION }}`)
    environment: ${{ inputs.ENVIRONMENT }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    container: rockylinux:9
    env:
      HZ_VERSION: ${{ inputs.HZ_VERSION }}
      PACKAGE_VERSION: ${{ inputs.PACKAGE_VERSION || inputs.HZ_VERSION }}
      HZ_DISTRIBUTION: ${{ inputs.HZ_DISTRIBUTION }}
      RPM_REPO: ${{ vars.RPM_REPO }}
    steps:
      - name: Checkout hazelcast-packaging repo
        uses: actions/checkout@v7

      - name: Checkout hazelcast-docker repo
        uses: actions/checkout@v7
        with:
          repository: hazelcast/hazelcast-docker
          path: 'hazelcast-docker'

      - name: Install Required tools
        run: |
          yum install \
            --assumeyes \
            gettext \
            jq \
            rpm-build \
            rpm-sign \
            systemd-rpm-macros \
            wget \
            which

      - name: Setup directories
        run: |
          mkdir -p build/rpmbuild/SOURCES/
          mkdir -p build/rpmbuild/rpm

      - name: Download the distribution file
        uses: hazelcast/docker-actions/download-hz-dist@master
        with:
          environment: ${{ inputs.ENVIRONMENT == 'test' && 'live' || inputs.ENVIRONMENT }}
          aws-role-to-assume: ${{ vars.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          distribution: ${{ env.HZ_DISTRIBUTION }}
          hz_version: ${{ env.HZ_VERSION }}
          packaging: "tar.gz"
          output_file: "build/rpmbuild/SOURCES/${{ env.HZ_DISTRIBUTION }}-${{ env.HZ_VERSION }}.tar.gz"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_DEV_INFRA_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: 'us-east-1'

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v3
        with:
          secret-ids: |
            SIGNING_KEY,SIGNING/GPG-KEY-2025
          parse-json-secrets: true

      - uses: hazelcast/docker-actions/get-jfrog-credentials@master
        id: authenticate-jfrog-write-dev-account
        with:
          aws-role-to-assume: ${{ vars.AWS_HAZELCAST_OIDC_GITHUB_ACTIONS_ROLE_ARN }}
          jfrog-oidc-provider-name: ${{ github.repository_owner }}-write-dev-account

      - name: Create RPM package
        id: create-rpm-package
        run: |
          source ./common.sh

          cp packages/common/hazelcast.service build/rpmbuild/SOURCES/hazelcast.service

          export RPM_BUILD_ROOT='$RPM_BUILD_ROOT'
          export FILENAME='${FILENAME}'
          export JAVA_VERSION
          envsubst <packages/rpm/hazelcast.spec >build/rpmbuild/rpm/hazelcast.spec

          rpmbuild \
            --define "_topdir $(realpath build/rpmbuild)" \
            -bb build/rpmbuild/rpm/hazelcast.spec

          echo "file=build/rpmbuild/RPMS/noarch/${HZ_DISTRIBUTION}-${RPM_PACKAGE_VERSION}.noarch.rpm" >> ${GITHUB_OUTPUT}
        env:
          JAVA_VERSION: ${{ inputs.JAVA_VERSION }}

      - name: Sign RPM package
        run: |
          source ./common.sh

          gpg --batch --import <<< "${SIGNING_KEY_PRIVATE_KEY}"
          echo 'allow-preset-passphrase' | tee ~/.gnupg/gpg-agent.conf
          gpg-connect-agent reloadagent /bye

          function get_gpg_key_data {
            local key=$1
            local property=$2

            gpg --show-keys --with-keygrip --with-colons <<< "${key}" | \
            awk -F: -v property="${property}" '$1==property {print $10; exit}'

            return 0
          }

          SIGNING_KEY_UID=$(get_gpg_key_data "${SIGNING_KEY_PRIVATE_KEY}" "uid")
          SIGNING_KEY_KEYGRIP=$(get_gpg_key_data "${SIGNING_KEY_PRIVATE_KEY}" "grp")

          /usr/libexec/gpg-preset-passphrase \
            --passphrase "${SIGNING_KEY_PASSPHRASE}" \
            --preset ${SIGNING_KEY_KEYGRIP}

          export GPG_TTY="" # to avoid 'warning: Could not set GPG_TTY to stdin: Inappropriate ioctl for device' for the next command
          rpm \
            --define "_gpg_name ${SIGNING_KEY_UID}" \
            --addsign "${{ steps.create-rpm-package.outputs.file }}"

      - name: Install Hazelcast from rpm
        run: |
          yum install \
            --assumeyes \
            --verbose \
            "${{ steps.create-rpm-package.outputs.file }}"

      - name: Start Hazelcast
        id: run-hazelcast
        background: true
        env:
          HZ_LICENSEKEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: |
          HAZELCAST_CONFIG="$(pwd)/config/integration-test-hazelcast.yaml" hz-start > hz.log 2>&1

      - name: Check Hazelcast health
        run: |
          ./check-hazelcast-health.sh "${HZ_DISTRIBUTION}" "${HZ_VERSION}"

      - name: Stop Hazelcast
        cancel: run-hazelcast

      - name: Uninstall Hazelcast from rpm
        run: |
          source ./common.sh
          yum remove --assumeyes ${HZ_DISTRIBUTION}-${RPM_PACKAGE_VERSION}

      - name: Upload RPM package
        run: |
          source ./common.sh

          jf rt upload \
            "${{ steps.create-rpm-package.outputs.file }}" \
            "${RPM_REPO}/${RELEASE_CHANNEL}/${HZ_DISTRIBUTION}-${RPM_PACKAGE_VERSION}.noarch.rpm"

      - name: Calculate YUM Repository Metadata
        run: |
          # https://docs.jfrog.com/artifactory/reference/calculateyumrepositorymetadata
          jf api --method POST "/artifactory/api/yum/${RPM_REPO}"

      - name: Remove rpm package from test repo
        if: ${{ inputs.ENVIRONMENT == 'test' && (success() || failure()) }}
        run: |
          source ./common.sh
          jf rt delete "${RPM_REPO}/${RELEASE_CHANNEL}/${HZ_DISTRIBUTION}-${RPM_PACKAGE_VERSION}.noarch.rpm"

      - name: Store logs as artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v7
        with:
          name: rpm-${{ env.HZ_DISTRIBUTION }}-hz.log
          path: hz.log
